### ISSUE TITLE
Performance discrepancy between the paper and codebase in GRF environment

### ISSUE THREAD

**Issue by LXXXXR** [lich14/CDS#11]
Dear authors,

Thank you for your awesome work. 

When I was running experiments for GRF experiment, I noticed a performance discrepancy between the paper(or the figure in the data folder) and the codebase. For example, I was running CDS on Qmix with `main.py --config=CDS_QMIX --env-config=academy_3_vs_1_with_keeper` and I only got 27.5% (averaged over 5 seeds) test average score after 4M environment timesteps. After I remove the CDS part, the performance drops to 7.5%. So this proves that CDS is indeed very useful in improving the QMIX performance. 

However, it would be really helpful if you could advise on the discrepancy in settings (for examples, batch size, number of parallel runs) between this codebase and the paper. Thank you very much.

**Comment by lich14** [comment]
Influenced by the uncontrolled stochastic random seeds that govern enemy behavior within the environment, the performance of the GRF algorithm can exhibit significant variability across different random seeds, and each run may even produce different results. I struggled to tune a set of hyperparameters two years ago with 5 random seeds, and running with this set of hyperparameters may produce worse or better results, as reflected in many papers comparing my algorithm.

Based on my current understanding, GRF in a random setting is not a good environment for verifying algorithms. The variance of this environment is large, which will cause great interference to the judgment of algorithm performance. If I want to propose a new algorithm now, I would turn off the randomness in the environment to verify the algorithm, or use SMAC and the updated SMAC V2 to verify the algorithm. The impact of different seeds in the SMAC environment will be significantly lower, and each run will give similar results

**Comment by LXXXXR** [comment]
Thank you very much for your kind reply. It surely helps a lot.
