### ISSUE TITLE
About CDS SMAC

### ISSUE THREAD

**Issue by yuanfei-Wang** [lich14/CDS#3]
Hi authors! I really appreciate that you released the code of CDS. Here I have a question when reproducing the results of CDS in the SMAC environment. I wonder if "qplex_qatten_sc2" is the CDS algorithm for SMAC? And what is "qplex_sc2_ablation"? Thanks!

**Comment by lich14** [comment]
You can run CDS with 'python3 src/main.py --config=qplex_qatten_sc2 --env-config=sc2_6h_vs_8z'.  "qplex_sc2_ablation" is useless here, which comes from the original code of QPLEX.
