### ISSUE TITLE
[bug] AttributeError: 'StarCraft2Env' object has no attribute 'get_unit_dim'

### ISSUE THREAD

**Issue by yifan123** [lich14/CDS#5]
https://github.com/lich14/CDS/blob/main/CDS_SMAC/QPLEX-master-SC2/pymarl-master/src/run.py#L106
There is no get_unit_dim() function in the standard smac env or qplex-modified smac env.
AttributeError: 'StarCraft2Env' object has no attribute 'get_unit_dim'
just change `args.unit_dim = runner.env.get_unit_dim()` to `args.unit_dim = env_info["unit_dim"]`

**Comment by lich14** [comment]
You can modify starcraft2.py as guidance in https://github.com/lich14/CDS/tree/main/CDS_SMAC

**Comment by yifan123** [comment]
> You can modify starcraft2.py as guidance in https://github.com/lich14/CDS/tree/main/CDS_SMAC

Thanks for your replay!

I just change `args.unit_dim = runner.env.get_unit_dim()` to `args.unit_dim = env_info["unit_dim"]`, and it works. Is there anything wrong with my approach?

**Comment by lich14** [comment]
There is nothing wrong with your approach. Maybe you have run some algorithms that needed unit_dim before, such as Qatten and Qplex. If someone hasn't run such an algorithm before, he or she should add the following codes in starcraft2.py in the python path.

``` 
self.unit_dim = 4 + self.shield_bits_ally + self.unit_type_bits
```
