### ISSUE TITLE
About implementing CDS on MAPPO

### ISSUE THREAD

**Issue by Atan03** [lich14/CDS#7]
Greetings！The paper and algo is really  helpful to QMIX and QPLEX.
After reading the repo's README, i find it is also said to be possible to implement CDS on MAPPO, but I
 have no idea about it. 
Could you provide some advice or guide about policy-based algorithm such as MAPPO？
Thanks！

**Comment by lich14** [comment]
The core contributions of CDS are: 
1. intrinsic rewards to achieve diversity 
2. policy representation structure for balancing diversity and sharing while providing enough representation capacity

The above two contributions are not limited to value-based methods. One can easily use them on policy-based algorithms. We have tried to run MAPPO on Google Research Football scenarios with **sparse reward settings**. Our experiment performance shows MAPPO can achieve a 100% winning rate on simple scenarios such as "academy 3 vs 1 with keeper", but cannot win on challenging scenarios such as "academy counterattack hard". After combined with CDS, MAPPO can achieve 20% winning rate on  "academy counterattack hard".

**Comment by Atan03** [comment]
thanks for your patience and insight！

**Comment by KaleabTessera** [comment]
Hi @lich14 @Atan03 :wave: , do either of you have a working implementation of CDS + PPO?
