### ISSUE TITLE
Can this running on windows10 without CUDA?

### ISSUE THREAD

**Issue by fighting-zz** [lich14/CDS#9]
![image](https://user-images.githubusercontent.com/84365395/180919252-53c71413-0328-4dc7-adf2-2f4c77f7a0e7.png)

**Comment by lich14** [comment]
It is obvious that you install pytorch with cpu only or your computer does not install cuda. If you want to run my code with cpu only, you can add _--use_cuda --GPU 'cpu'_ at the end of the command
